/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.7.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the scala Plugin to add support for Scala.
    scala

    // Apply the application plugin to add support for building a CLI application in Java.
    application
    alias(libs.plugins.spotbugs)
    alias(libs.plugins.scalafmt)

    /*
    The Scalastyle plugin’s latest published version is 3.5.0, but it still uses the deprecated API.
    Scalastyle is effectively unmaintained. (https://docs.fukuii.com/reports/STATIC_ANALYSIS_INVENTORY/)
    */
    //alias(libs.plugins.scalastyle)
}



spotbugs {
    ignoreFailures = false
}

tasks.withType<com.github.spotbugs.snom.SpotBugsTask>().configureEach {
    reports {
        create("html") {
            required.set(true)
        }
    }
}
tasks.named("check") {
    dependsOn("checkScalafmtAll")
}


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()

    gradlePluginPortal()
}

dependencies {
    // Use Scala 2.13 in our library project
    implementation(libs.scala.library)

    // This dependency is used by the application.
    implementation(libs.guava)

    // Use Scalatest for testing our library
    testImplementation(libs.junit)
    testImplementation(libs.scalatest.v2.v13)
    testImplementation(libs.junit.v4.v13.v2.v13)

    // Need scala-xml at test runtime
    testRuntimeOnly(libs.scala.xml.v2.v13)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "it.unibo.splague.App"
}
