/*
 * This file was generated by the Gradle 'init' task, rewritten for Scala 3.
 *
 * This generated file contains a sample Scala application project to get you started.
 * For more details on building Java & JVM projects, please refer to
 * https://docs.gradle.org/9.7.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the scala Plugin to add support for Scala.
    scala

    // Apply the application plugin to add support for building a CLI application in Java.
    application

    alias(libs.plugins.spotbugs)
    alias(libs.plugins.scalafmt)

    /*
     * The Scalastyle plugin's latest published version is 3.5.0, but it still uses the deprecated API.
     * Scalastyle is effectively unmaintained. (https://docs.fukuii.com/reports/STATIC_ANALYSIS_INVENTORY/)
     */
    // alias(libs.plugins.scalastyle)
}

// Pin the Scala 3 compiler version explicitly.
// Using the Scala 3 "Next" line (3.8.4) instead of the 3.3 LTS line.
// Scala 3.8 requires JDK 17+ at minimum; this project already targets JDK 21, so it's compatible.
scala {
    scalaVersion = "3.8.4"
}

spotbugs {
    ignoreFailures = false
    excludeFilter = file("config/spotbugs/exclude.xml")
}

tasks.withType<com.github.spotbugs.snom.SpotBugsTask>().configureEach {
    reports {
        create("html") {
            required.set(true)
        }
    }
}

tasks.named("check") {
    dependsOn("checkScalafmtAll")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    gradlePluginPortal()
}

tasks.withType<ScalaCompile>().configureEach {
    scalaCompileOptions.additionalParameters = listOf("-release", "21")
}

dependencies {
    // Use Scala 3 in our library project
    implementation(libs.scala3library)

    // This dependency is used by the application.
    implementation(libs.guava)

    // Support for Monad[_]
    implementation(libs.scalazlibrary)

    implementation("org.scala-lang.modules:scala-swing_3:3.0.0")

    // Use Scalatest for testing our library.
    // scalactic is pinned explicitly to match scalatest's version, since
    // a transitive version mismatch between the two is what causes
    // "No given instance of type org.scalactic.source.Position was found"
    // for macro-based methods like assert().
    testImplementation(libs.junit)
    testImplementation(libs.scalatest)
    testImplementation(libs.scalactic)
    testImplementation(libs.scalatestplusjunit)



    // Need scala-xml at test runtime
    testRuntimeOnly(libs.scalaxml)


}

java {
    // Apply a specific Java toolchain to ease working on different environments.
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "it.unibo.splague.App"
}
