/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unibo.splague

import it.unibo.splague.update.Mvu.ModelState
import it.unibo.splague.view.{MainView, Renderer}
import it.unibo.splague.update.Runtime

object App:

  def main(args: Array[String]): Unit = {

    val model: ModelState = ModelState.init()

    val view: Renderer = new MainView

    val runtime: Runtime = new Runtime(model, view)

    println(greeting())
  }

  def greeting(): String = "Hello, world!"
