/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unibo.splague

import it.unibo.splague.model.ModelState
import it.unibo.splague.view.{MainView, Renderer}
import it.unibo.splague.update.Runtime

// $COVERAGE-OFF$
object App:

  def main(args: Array[String]): Unit = {

    val model: AppState = AppState.init(ModelState())

    val view: Renderer = new MainView

    val runtime: Runtime = new Runtime(model, view)

    runtime.start()

    println(greeting())
  }

  def greeting(): String = "Hello, world!"
// $COVERAGE-ON$
